FROM debian:12-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    samba winbind libnss-winbind libpam-winbind krb5-user smbclient \
    samba-dsdb-modules samba-vfs-modules dnsutils netcat-openbsd procps \
 && rm -rf /var/lib/apt/lists/* /etc/samba/smb.conf
COPY member-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
